version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: lighthouse_db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: lighthouse
      MYSQL_USER: okarin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
